version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    environment:
      - JWT_SECRET=topsecret123
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/appdb

  frontend:
    build: ./frontend
    ports:
      - '3001:3000'
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://localhost:3000

  postgres:
    image: postgres:14
    container_name: pg_auth
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: