version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      JWT_SECRET: topsecret123
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/appdb

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    environment:
      REACT_APP_API_URL: http://backend:3000

volumes:
  pgdata: